steps: 
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker login --username=$$DOCKERHUB_USERNAME --password=$$DOCKERHUB_TOKEN
        docker buildx create --name=container --driver=docker-container --use
        docker buildx build -f ./dockerfiles/Dockerfile.pyenv-poetry \
        -t drxc/python:${_PYTHONVERSION}-ubuntu${_BASE_VERSION}-${_DEVICE} \
        --builder=container \
        --platform=linux/amd64,linux/arm64 \
        --build-arg PYTHONVERSION=${_PYTHONVERSION} \
        --build-arg BASE_VERSION=${_BASE_VERSION} \
        --build-arg DEVICE=${_DEVICE} \
        --build-arg CUDA_VERSION=${_CUDA_VERSION} \
        --cache-to "type=registry,ref=drxc/python:${_PYTHONVERSION}-ubuntu${_BASE_VERSION}-${_DEVICE}-cache,mode=max" \
        --cache-from "type=registry,ref=drxc/python:${_PYTHONVERSION}-ubuntu${_BASE_VERSION}-${_DEVICE}-cache" \
        --push .
    secretEnv: ['DOCKERHUB_USERNAME', 'DOCKERHUB_TOKEN']
logsBucket: ${_LOG_BUCKET}
options:
  machineType: 'E2_HIGHCPU_8'
availableSecrets:
  secretManager:
  - versionName: projects/PROJECT_ID/secrets/DOCKERHUB_TOKEN/versions/1
    env: 'DOCKERHUB_TOKEN'
  - versionName: projects/PROJECT_ID/secrets/DOCKERHUB_USERNAME/versions/1
    env: 'DOCKERHUB_USERNAME'
  