name: Build and Push images

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - dockerfiles/Dockerfile.pyenv-poetry
    

jobs:
  build-base-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: dockerfiles/Dockerfile.pyenv-poetry
          push: true
          tags: drxc/python:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_CACHE_TAG }}
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_CACHE_TAG }},mode=max
